### ISSUE TITLE
ArgumentNullException in AsyncOverloadsAvailableAnalyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/SharpSource#24]
```
'SharpSource.Diagnostics.CorrectTPLMethodsInAsyncContext.AsyncOverloadsAvailableAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: syntax'.	Hudl.Clips		1	Active	Analyzer 'SharpSource.Diagnostics.CorrectTPLMethodsInAsyncContext.AsyncOverloadsAvailableAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Hudl.Clips
SyntaxTree: C:\Source\hudl-clips\Hudl.Clips\Utility\Cache\ContextCacheHelper.cs
SyntaxNode: public async Task<List<VideoDto ... [MethodDeclarationSyntax]@[12304..13297) (312,8)-(331,9)

System.ArgumentNullException: Value cannot be null.
Parameter name: syntax
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at SharpSource.Diagnostics.CorrectTPLMethodsInAsyncContext.AsyncOverloadsAvailableAnalyzer.CheckIfOverloadAvailable(IdentifierNameSyntax invokedFunction, SyntaxNodeAnalysisContext context)
   at SharpSource.Diagnostics.CorrectTPLMethodsInAsyncContext.AsyncOverloadsAvailableAnalyzer.AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__58`1.<ExecuteSyntaxNodeAction>b__58_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by Vannevelj** [comment]
Appears to be caused by a `ThrowsAsync<T>` statement which is a `GenericNameIdentifier`
