### ISSUE TITLE
ArgumentOutOfRangeException on GetHashCodeRefersToMutableMemberAnalyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/SharpSource#90]
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'SharpSource.Diagnostics.GetHashCodeRefersToMutableMemberAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: span'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.CSharp
SyntaxTree: C:\source\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundDagEvaluation.cs
SyntaxNode: public override int GetHashCode ... [MethodDeclarationSyntax]@[2886..3029) (69,8)-(72,9)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie)
   at SharpSource.Diagnostics.GetHashCodeRefersToMutableMemberAnalyzer.AnalyzeMethod(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: SS008	Microsoft.CodeAnalysis.CSharp (netcoreapp3.1)		1	Active	Analyzer 'SharpSource.Diagnostics.GetHashCodeRefersToMutableMemberAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.CSharp
SyntaxTree: C:\source\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundDagEvaluation.cs
SyntaxNode: public override int GetHashCode ... [MethodDeclarationSyntax]@[2886..3029) (69,8)-(72,9)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie)
   at SharpSource.Diagnostics.GetHashCodeRefersToMutableMemberAnalyzer.AnalyzeMethod(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

Appears to be related to `partial` classes

**Comment by Vannevelj** [comment]
Duplicate of #32
